export const guestsList = [
    {
        invitation_id: "f282bb98-6d9c-446d-8ef6-1dacff261732",
        password: "OV1-OBk",
        phone_number: "+527669194896",
        name: "Isabella Ruiz Reyes",
        state: "creado",
        last_action: "creado",
        tier: "D",
        tag: "Amigos",
        table: 90,
        notes: null,
        meal: null,
        side: "Ale",
        companion_id: null,
        ticket: true,
        has_companion: false,
        last_action_by: false,
        type: "female"
    },
    {
        invitation_id: "f282bb98-6d9c-446d-8ef6-1dacff261732",
        password: "I68-k80",
        phone_number: "+528056820175",
        name: "Dani Rivera Morales",
        state: "creado",
        last_action: "creado",
        tier: "B",
        tag: "Amigos",
        table: 91,
        notes: null,
        meal: null,
        side: "Santiago",
        companion_id: null,
        ticket: true,
        has_companion: false,
        last_action_by: false,
        type: "child"
    },
    {
        invitation_id: "f282bb98-6d9c-446d-8ef6-1dacff261732",
        password: "Po7-Acn",
        phone_number: "+526618695724",
        name: "Mariana Mendoza Torres",
        state: "creado",
        last_action: "creado",
        tier: "A",
        tag: "Familia",
        table: 18,
        notes: null,
        meal: null,
        side: "Santiago",
        companion_id: null,
        ticket: true,
        has_companion: false,
        last_action_by: false,
        type: "female"
    },
    {
        invitation_id: "f282bb98-6d9c-446d-8ef6-1dacff261732",
        password: "22A-TPy",
        phone_number: "+524741253137",
        name: "Emiliano Reyes Martínez",
        state: "confirmado",
        last_action: "esperando",
        tier: "B",
        tag: "Trabajo",
        table: 13,
        notes: null,
        meal: null,
        side: "Santiago",
        companion_id: null,
        ticket: true,
        has_companion: false,
        last_action_by: false,
        type: "male"
    },
    {
        invitation_id: "f282bb98-6d9c-446d-8ef6-1dacff261732",
        password: "qnU-2ZG",
        phone_number: "+520077732175",
        name: "Pablo López Navarro",
        state: "creado",
        last_action: "creado",
        tier: "A",
        tag: "Trabajo",
        table: 21,
        notes: null,
        meal: null,
        side: "Ale",
        companion_id: null,
        ticket: true,
        has_companion: false,
        last_action_by: false,
        type: "male"
    },
    {
        invitation_id: "f282bb98-6d9c-446d-8ef6-1dacff261732",
        password: "2W4-0rK",
        phone_number: "+526214555213",
        name: "Regina Ruiz Reyes",
        state: "esperando",
        last_action: "creado",
        tier: "B",
        tag: "Familia",
        table: 89,
        notes: null,
        meal: null,
        side: "Ale",
        companion_id: null,
        ticket: true,
        has_companion: false,
        last_action_by: false,
        type: "female"
    },
    {
        invitation_id: "f282bb98-6d9c-446d-8ef6-1dacff261732",
        password: "oG1-Z2W",
        phone_number: "+526525518726",
        name: "Samuel Ruiz Reyes",
        state: "confirmado",
        last_action: "esperando",
        tier: "B",
        tag: "Trabajo",
        table: 87,
        notes: null,
        meal: null,
        side: "Ale",
        companion_id: null,
        ticket: true,
        has_companion: false,
        last_action_by: false,
        type: "male"
    },
    {
        invitation_id: "f282bb98-6d9c-446d-8ef6-1dacff261732",
        password: "WmQ-zC4",
        phone_number: "+520123129354",
        name: "Ximena Ortiz Martínez",
        state: "confirmado",
        last_action: "esperando",
        tier: "A",
        tag: "Amigos",
        table: 12,
        notes: null,
        meal: null,
        side: "Ale",
        companion_id: null,
        ticket: true,
        has_companion: false,
        last_action_by: false,
        type: "female"
    },
    {
        invitation_id: "f282bb98-6d9c-446d-8ef6-1dacff261732",
        password: "WBf-bZa",
        phone_number: "+520623145112",
        name: "Camila Flores Romero",
        state: "confirmado",
        last_action: "esperando",
        tier: "A",
        tag: "Trabajo",
        table: 18,
        notes: null,
        meal: null,
        side: "Ale",
        companion_id: null,
        ticket: true,
        has_companion: false,
        last_action_by: false,
        type: "female"
    },
    {
        invitation_id: "f282bb98-6d9c-446d-8ef6-1dacff261732",
        password: "4mX-RK8",
        phone_number: "+528236493852",
        name: "Camila Díaz González",
        state: "confirmado",
        last_action: "esperando",
        tier: "A",
        tag: "Amigos",
        table: 92,
        notes: null,
        meal: null,
        side: "Santiago",
        companion_id: null,
        ticket: true,
        has_companion: false,
        last_action_by: false,
        type: "female"
    },
    {
        invitation_id: "f282bb98-6d9c-446d-8ef6-1dacff261732",
        password: "qN4-4wt",
        phone_number: "+529934160097",
        name: "Valentina Mendoza García",
        state: "esperando",
        last_action: "creado",
        tier: "A",
        tag: "Amigos",
        table: 21,
        notes: null,
        meal: null,
        side: "Santiago",
        companion_id: null,
        ticket: true,
        has_companion: false,
        last_action_by: false,
        type: "female"
    },
    {
        invitation_id: "f282bb98-6d9c-446d-8ef6-1dacff261732",
        password: "n1Z-aV4",
        phone_number: "+526052970050",
        name: "Mateo Torres Ruiz",
        state: "confirmado",
        last_action: "esperando",
        tier: "C",
        tag: "Amigos",
        table: 93,
        notes: null,
        meal: null,
        side: "Ale",
        companion_id: null,
        ticket: true,
        has_companion: false,
        last_action_by: false,
        type: "male"
    },
    {
        invitation_id: "f282bb98-6d9c-446d-8ef6-1dacff261732",
        password: "ZqQ-0zM",
        phone_number: "+529211200890",
        name: "Natalia Romero García",
        state: "creado",
        last_action: "creado",
        tier: "A",
        tag: "Familia",
        table: 89,
        notes: null,
        meal: null,
        side: "Ale",
        companion_id: null,
        ticket: true,
        has_companion: false,
        last_action_by: false,
        type: "female"
    },
    {
        invitation_id: "f282bb98-6d9c-446d-8ef6-1dacff261732",
        password: "Iac-1SL",
        phone_number: "+529966963657",
        name: "Andrés Ramírez Gómez",
        state: "creado",
        last_action: "creado",
        tier: "A",
        tag: "Familia",
        table: 20,
        notes: null,
        meal: null,
        side: "Ale",
        companion_id: null,
        ticket: true,
        has_companion: false,
        last_action_by: false,
        type: "male"
    },
    {
        invitation_id: "f282bb98-6d9c-446d-8ef6-1dacff261732",
        password: "7fB-vFQ",
        phone_number: "+526760344689",
        name: "Carla Cruz Rivera",
        state: "confirmado",
        last_action: "esperando",
        tier: "A",
        tag: "Familia",
        table: 90,
        notes: null,
        meal: null,
        side: "Ale",
        companion_id: null,
        ticket: true,
        has_companion: false,
        last_action_by: false,
        type: "female"
    },
    {
        invitation_id: "f282bb98-6d9c-446d-8ef6-1dacff261732",
        password: "N3z-v1M",
        phone_number: "+523307887947",
        name: "Mariana Morales Hernández",
        state: "confirmado",
        last_action: "esperando",
        tier: "D",
        tag: "Trabajo",
        table: 87,
        notes: null,
        meal: null,
        side: "Ale",
        companion_id: null,
        ticket: true,
        has_companion: false,
        last_action_by: false,
        type: "female"
    },
    {
        invitation_id: "f282bb98-6d9c-446d-8ef6-1dacff261732",
        password: "iF4-n4j",
        phone_number: "+523124029299",
        name: "Daniel Ruiz Ramírez",
        state: "creado",
        last_action: "creado",
        tier: "B",
        tag: "Familia",
        table: 19,
        notes: null,
        meal: null,
        side: "Ale",
        companion_id: null,
        ticket: true,
        has_companion: false,
        last_action_by: false,
        type: "male"
    },
    {
        invitation_id: "f282bb98-6d9c-446d-8ef6-1dacff261732",
        password: "psR-7nV",
        phone_number: "+521717031365",
        name: "Valentina Flores Mendoza",
        state: "confirmado",
        last_action: "esperando",
        tier: "A",
        tag: "Familia",
        table: 91,
        notes: null,
        meal: null,
        side: "Santiago",
        companion_id: null,
        ticket: true,
        has_companion: false,
        last_action_by: false,
        type: "female"
    },
    {
        invitation_id: "f282bb98-6d9c-446d-8ef6-1dacff261732",
        password: "Ek9-L6h",
        phone_number: "+526818074541",
        name: "Alejandro Cruz Ruiz",
        state: "esperando",
        last_action: "creado",
        tier: "A",
        tag: "Trabajo",
        table: 14,
        notes: null,
        meal: null,
        side: "Santiago",
        companion_id: null,
        ticket: true,
        has_companion: false,
        last_action_by: false,
        type: "male"
    },
    {
        invitation_id: "f282bb98-6d9c-446d-8ef6-1dacff261732",
        password: "5vL-kzS",
        phone_number: "+521271104954",
        name: "Camila Martínez Navarro",
        state: "confirmado",
        last_action: "esperando",
        tier: "A",
        tag: "Familia",
        table: 88,
        notes: null,
        meal: null,
        side: "Ale",
        companion_id: null,
        ticket: true,
        has_companion: false,
        last_action_by: false,
        type: "female"
    },
    {
        invitation_id: "f282bb98-6d9c-446d-8ef6-1dacff261732",
        password: "bVq-PZ8",
        phone_number: "+522666135404",
        name: "Paula Mendoza Ruiz",
        state: "confirmado",
        last_action: "esperando",
        tier: "A",
        tag: "Amigos",
        table: 92,
        notes: null,
        meal: null,
        side: "Santiago",
        companion_id: null,
        ticket: true,
        has_companion: false,
        last_action_by: false,
        type: "female"
    },
    {
        invitation_id: "f282bb98-6d9c-446d-8ef6-1dacff261732",
        password: "1wM-Mr9",
        phone_number: "+522304227872",
        name: "Iván Ruiz Ruiz",
        state: "esperando",
        last_action: "creado",
        tier: "B",
        tag: "Familia",
        table: 18,
        notes: null,
        meal: null,
        side: "Ale",
        companion_id: null,
        ticket: true,
        has_companion: false,
        last_action_by: false,
        type: "male"
    },
    {
        invitation_id: "f282bb98-6d9c-446d-8ef6-1dacff261732",
        password: "FcX-9Wm",
        phone_number: "+529721894886",
        name: "Andrea Ramírez Pérez",
        state: "creado",
        last_action: "creado",
        tier: "A",
        tag: "Familia",
        table: 21,
        notes: null,
        meal: null,
        side: "Santiago",
        companion_id: null,
        ticket: true,
        has_companion: false,
        last_action_by: false,
        type: "female"
    },
    {
        invitation_id: "f282bb98-6d9c-446d-8ef6-1dacff261732",
        password: "B9C-aJ8",
        phone_number: "+526716409791",
        name: "Luis Vázquez Ramírez",
        state: "esperando",
        last_action: "creado",
        tier: "D",
        tag: "Familia",
        table: 87,
        notes: null,
        meal: null,
        side: "Santiago",
        companion_id: null,
        ticket: true,
        has_companion: false,
        last_action_by: false,
        type: "male"
    },
    {
        invitation_id: "f282bb98-6d9c-446d-8ef6-1dacff261732",
        password: "Jr7-2xx",
        phone_number: "+527173365288",
        name: "Valentina Gómez García",
        state: "confirmado",
        last_action: "esperando",
        tier: "B",
        tag: "Amigos",
        table: 13,
        notes: null,
        meal: null,
        side: "Ale",
        companion_id: null,
        ticket: true,
        has_companion: false,
        last_action_by: false,
        type: "female"
    },
    {
        invitation_id: "f282bb98-6d9c-446d-8ef6-1dacff261732",
        password: "f7l-v4S",
        phone_number: "+522202356437",
        name: "Daniela Díaz López",
        state: "confirmado",
        last_action: "esperando",
        tier: "A",
        tag: "Trabajo",
        table: 14,
        notes: null,
        meal: null,
        side: "Santiago",
        companion_id: null,
        ticket: true,
        has_companion: false,
        last_action_by: false,
        type: "female"
    },
    {
        invitation_id: "f282bb98-6d9c-446d-8ef6-1dacff261732",
        password: "l8A-oR7",
        phone_number: "+529475488355",
        name: "Mía Gómez Díaz",
        state: "confirmado",
        last_action: "esperando",
        tier: "B",
        tag: "Trabajo",
        table: 92,
        notes: null,
        meal: null,
        side: "Ale",
        companion_id: null,
        ticket: true,
        has_companion: false,
        last_action_by: false,
        type: "female"
    },
    {
        invitation_id: "f282bb98-6d9c-446d-8ef6-1dacff261732",
        password: "Vha-vnC",
        phone_number: "+529526178113",
        name: "Gael Romero Flores",
        state: "creado",
        last_action: "creado",
        tier: "B",
        tag: "Trabajo",
        table: 12,
        notes: null,
        meal: null,
        side: "Santiago",
        companion_id: null,
        ticket: true,
        has_companion: false,
        last_action_by: false,
        type: "male"
    },
    {
        invitation_id: "f282bb98-6d9c-446d-8ef6-1dacff261732",
        password: "r9P-fW9",
        phone_number: "+525418259643",
        name: "Lucía Ortiz Aguilar",
        state: "creado",
        last_action: "creado",
        tier: "B",
        tag: "Trabajo",
        table: 19,
        notes: null,
        meal: null,
        side: "Ale",
        companion_id: null,
        ticket: true,
        has_companion: false,
        last_action_by: false,
        type: "female"
    },
    {
        invitation_id: "f282bb98-6d9c-446d-8ef6-1dacff261732",
        password: "dQ4-TmV",
        phone_number: "+527639981271",
        name: "Camila Ramírez Hernández",
        state: "esperando",
        last_action: "creado",
        tier: "C",
        tag: "Familia",
        table: 93,
        notes: null,
        meal: null,
        side: "Ale",
        companion_id: null,
        ticket: true,
        has_companion: false,
        last_action_by: false,
        type: "female"
    },
    {
        invitation_id: "f282bb98-6d9c-446d-8ef6-1dacff261732",
        password: "Nn7-Qtw",
        phone_number: "+523512954915",
        name: "Victoria Torres Gómez",
        state: "confirmado",
        last_action: "esperando",
        tier: "C",
        tag: "Trabajo",
        table: 91,
        notes: null,
        meal: null,
        side: "Ale",
        companion_id: null,
        ticket: true,
        has_companion: false,
        last_action_by: false,
        type: "female"
    },
    {
        invitation_id: "f282bb98-6d9c-446d-8ef6-1dacff261732",
        password: "M2j-vMb",
        phone_number: "+528380770443",
        name: "Andrea Reyes Mendoza",
        state: "confirmado",
        last_action: "esperando",
        tier: "A",
        tag: "Familia",
        table: 20,
        notes: null,
        meal: null,
        side: "Santiago",
        companion_id: null,
        ticket: true,
        has_companion: false,
        last_action_by: false,
        type: "female"
    },
    {
        invitation_id: "f282bb98-6d9c-446d-8ef6-1dacff261732",
        password: "g4N-FfM",
        phone_number: "+523353047445",
        name: "Hugo Aguilar Hernández",
        state: "confirmado",
        last_action: "esperando",
        tier: "A",
        tag: "Trabajo",
        table: 20,
        notes: null,
        meal: null,
        side: "Santiago",
        companion_id: null,
        ticket: true,
        has_companion: false,
        last_action_by: false,
        type: "male"
    },
    {
        invitation_id: "f282bb98-6d9c-446d-8ef6-1dacff261732",
        password: "r6q-v9M",
        phone_number: "+524526497441",
        name: "Natalia Hernández Díaz",
        state: "esperando",
        last_action: "creado",
        tier: "A",
        tag: "Familia",
        table: 88,
        notes: null,
        meal: null,
        side: "Ale",
        companion_id: null,
        ticket: true,
        has_companion: false,
        last_action_by: false,
        type: "female"
    },
    {
        invitation_id: "f282bb98-6d9c-446d-8ef6-1dacff261732",
        password: "5Tg-8Nw",
        phone_number: "+529203323491",
        name: "Adrián Mendoza Díaz",
        state: "confirmado",
        last_action: "esperando",
        tier: "B",
        tag: "Trabajo",
        table: 88,
        notes: null,
        meal: null,
        side: "Ale",
        companion_id: null,
        ticket: true,
        has_companion: false,
        last_action_by: false,
        type: "male"
    },
    {
        invitation_id: "f282bb98-6d9c-446d-8ef6-1dacff261732",
        password: "t8A-Jz1",
        phone_number: "+528303858084",
        name: "Ana Sánchez Martínez",
        state: "confirmado",
        last_action: "esperando",
        tier: "A",
        tag: "Amigos",
        table: 90,
        notes: null,
        meal: null,
        side: "Santiago",
        companion_id: null,
        ticket: true,
        has_companion: false,
        last_action_by: false,
        type: "female"
    },
    {
        invitation_id: "f282bb98-6d9c-446d-8ef6-1dacff261732",
        password: "Q4n-fkP",
        phone_number: "+522355032757",
        name: "Elena Ruiz López",
        state: "creado",
        last_action: "creado",
        tier: "C",
        tag: "Trabajo",
        table: 14,
        notes: null,
        meal: null,
        side: "Santiago",
        companion_id: null,
        ticket: true,
        has_companion: false,
        last_action_by: false,
        type: "female"
    },
    {
        invitation_id: "f282bb98-6d9c-446d-8ef6-1dacff261732",
        password: "F5a-YrM",
        phone_number: "+522701155754",
        name: "Mía Ruiz Rivera",
        state: "confirmado",
        last_action: "esperando",
        tier: "A",
        tag: "Trabajo",
        table: 93,
        notes: null,
        meal: null,
        side: "Ale",
        companion_id: null,
        ticket: true,
        has_companion: false,
        last_action_by: false,
        type: "female"
    },
    {
        invitation_id: "f282bb98-6d9c-446d-8ef6-1dacff261732",
        password: "hG2-jWm",
        phone_number: "+527674051593",
        name: "Alex Ramírez Rivera",
        state: "confirmado",
        last_action: "esperando",
        tier: "B",
        tag: "Familia",
        table: 92,
        notes: null,
        meal: null,
        side: "Ale",
        companion_id: null,
        ticket: true,
        has_companion: false,
        last_action_by: false,
        type: "child"
    },
    {
        invitation_id: "f282bb98-6d9c-446d-8ef6-1dacff261732",
        password: "p0A-Tv9",
        phone_number: "+527386517471",
        name: "Sara Torres Rivera",
        state: "esperando",
        last_action: "creado",
        tier: "A",
        tag: "Familia",
        table: 13,
        notes: null,
        meal: null,
        side: "Santiago",
        companion_id: null,
        ticket: true,
        has_companion: false,
        last_action_by: false,
        type: "female"
    },
    {
        invitation_id: "f282bb98-6d9c-446d-8ef6-1dacff261732",
        password: "1pD-fxA",
        phone_number: "+526870578701",
        name: "Valentina Rivera Díaz",
        state: "creado",
        last_action: "creado",
        tier: "B",
        tag: "Familia",
        table: 21,
        notes: null,
        meal: null,
        side: "Ale",
        companion_id: null,
        ticket: true,
        has_companion: false,
        last_action_by: false,
        type: "female"
    },
    {
        invitation_id: "f282bb98-6d9c-446d-8ef6-1dacff261732",
        password: "R7w-cK3",
        phone_number: "+523270832502",
        name: "Leonardo Ruiz Romero",
        state: "confirmado",
        last_action: "esperando",
        tier: "A",
        tag: "Amigos",
        table: 92,
        notes: null,
        meal: null,
        side: "Santiago",
        companion_id: null,
        ticket: true,
        has_companion: false,
        last_action_by: false,
        type: "male"
    },
    {
        invitation_id: "f282bb98-6d9c-446d-8ef6-1dacff261732",
        password: "9mJ-TqN",
        phone_number: "+522082164071",
        name: "Fernanda Gómez Martínez",
        state: "confirmado",
        last_action: "esperando",
        tier: "A",
        tag: "Trabajo",
        table: 14,
        notes: null,
        meal: null,
        side: "Ale",
        companion_id: null,
        ticket: true,
        has_companion: false,
        last_action_by: false,
        type: "female"
    },
    {
        invitation_id: "f282bb98-6d9c-446d-8ef6-1dacff261732",
        password: "Ly6-Xs7",
        phone_number: "+528825167117",
        name: "Diego Martínez Cruz",
        state: "creado",
        last_action: "creado",
        tier: "B",
        tag: "Amigos",
        table: 19,
        notes: null,
        meal: null,
        side: "Santiago",
        companion_id: null,
        ticket: true,
        has_companion: false,
        last_action_by: false,
        type: "male"
    },
    {
        invitation_id: "f282bb98-6d9c-446d-8ef6-1dacff261732",
        password: "Y6a-P2f",
        phone_number: "+522565514018",
        name: "Natalia Díaz Hernández",
        state: "confirmado",
        last_action: "esperando",
        tier: "B",
        tag: "Trabajo",
        table: 91,
        notes: null,
        meal: null,
        side: "Ale",
        companion_id: null,
        ticket: true,
        has_companion: false,
        last_action_by: false,
        type: "female"
    },
    {
        invitation_id: "f282bb98-6d9c-446d-8ef6-1dacff261732",
        password: "Jz2-rFx",
        phone_number: "+521016332945",
        name: "Mía López González",
        state: "confirmado",
        last_action: "esperando",
        tier: "B",
        tag: "Trabajo",
        table: 93,
        notes: null,
        meal: null,
        side: "Ale",
        companion_id: null,
        ticket: true,
        has_companion: false,
        last_action_by: false,
        type: "female"
    },
    {
        invitation_id: "f282bb98-6d9c-446d-8ef6-1dacff261732",
        password: "X9s-Q2m",
        phone_number: "+527274930253",
        name: "Renata López Ruiz",
        state: "esperando",
        last_action: "creado",
        tier: "D",
        tag: "Familia",
        table: 20,
        notes: null,
        meal: null,
        side: "Santiago",
        companion_id: null,
        ticket: true,
        has_companion: false,
        last_action_by: false,
        type: "female"
    },
    {
        invitation_id: "f282bb98-6d9c-446d-8ef6-1dacff261732",
        password: "r7D-LgQ",
        phone_number: "+524633356944",
        name: "Isabella Vázquez López",
        state: "creado",
        last_action: "creado",
        tier: "A",
        tag: "Trabajo",
        table: 89,
        notes: null,
        meal: null,
        side: "Ale",
        companion_id: null,
        ticket: true,
        has_companion: false,
        last_action_by: false,
        type: "female"
    },
    {
        invitation_id: "f282bb98-6d9c-446d-8ef6-1dacff261732",
        password: "mP4-csN",
        phone_number: "+521684386801",
        name: "Mateo Sánchez Torres",
        state: "confirmado",
        last_action: "esperando",
        tier: "A",
        tag: "Amigos",
        table: 90,
        notes: null,
        meal: null,
        side: "Santiago",
        companion_id: null,
        ticket: true,
        has_companion: false,
        last_action_by: false,
        type: "male"
    },
    {
        invitation_id: "f282bb98-6d9c-446d-8ef6-1dacff261732",
        password: "sA8-Qw2",
        phone_number: "+528915338236",
        name: "Sofía Navarro López",
        state: "confirmado",
        last_action: "esperando",
        tier: "A",
        tag: "Familia",
        table: 18,
        notes: null,
        meal: null,
        side: "Ale",
        companion_id: null,
        ticket: true,
        has_companion: false,
        last_action_by: false,
        type: "female"
    },
    {
        invitation_id: "f282bb98-6d9c-446d-8ef6-1dacff261732",
        password: "H2n-Mz8",
        phone_number: "+528046898882",
        name: "Joaquín Rivera Ruiz",
        state: "esperando",
        last_action: "creado",
        tier: "A",
        tag: "Amigos",
        table: 87,
        notes: null,
        meal: null,
        side: "Santiago",
        companion_id: null,
        ticket: true,
        has_companion: false,
        last_action_by: false,
        type: "male"
    },
    {
        invitation_id: "f282bb98-6d9c-446d-8ef6-1dacff261732",
        password: "u2R-Wp7",
        phone_number: "+520119509945",
        name: "Regina Ruiz Torres",
        state: "confirmado",
        last_action: "esperando",
        tier: "B",
        tag: "Trabajo",
        table: 13,
        notes: null,
        meal: null,
        side: "Ale",
        companion_id: null,
        ticket: true,
        has_companion: false,
        last_action_by: false,
        type: "female"
    },
    {
        invitation_id: "f282bb98-6d9c-446d-8ef6-1dacff261732",
        password: "N4x-Jh3",
        phone_number: "+520553349424",
        name: "Daniela Gómez Ruiz",
        state: "confirmado",
        last_action: "esperando",
        tier: "C",
        tag: "Amigos",
        table: 12,
        notes: null,
        meal: null,
        side: "Ale",
        companion_id: null,
        ticket: true,
        has_companion: false,
        last_action_by: false,
        type: "female"
    },
    {
        invitation_id: "f282bb98-6d9c-446d-8ef6-1dacff261732",
        password: "Gq3-Lp0",
        phone_number: "+522313812616",
        name: "Luna González Reyes",
        state: "creado",
        last_action: "creado",
        tier: "A",
        tag: "Familia",
        table: 18,
        notes: null,
        meal: null,
        side: "Santiago",
        companion_id: null,
        ticket: true,
        has_companion: false,
        last_action_by: false,
        type: "child"
    },
    {
        invitation_id: "f282bb98-6d9c-446d-8ef6-1dacff261732",
        password: "pR8-Nk4",
        phone_number: "+527731752015",
        name: "Leonardo Ruiz Morales",
        state: "esperando",
        last_action: "creado",
        tier: "B",
        tag: "Amigos",
        table: 88,
        notes: null,
        meal: null,
        side: "Ale",
        companion_id: null,
        ticket: true,
        has_companion: false,
        last_action_by: false,
        type: "male"
    },
    {
        invitation_id: "f282bb98-6d9c-446d-8ef6-1dacff261732",
        password: "L0z-Vc2",
        phone_number: "+523815401246",
        name: "Ximena Cruz Díaz",
        state: "confirmado",
        last_action: "esperando",
        tier: "B",
        tag: "Familia",
        table: 90,
        notes: null,
        meal: null,
        side: "Ale",
        companion_id: null,
        ticket: true,
        has_companion: false,
        last_action_by: false,
        type: "female"
    },
    {
        invitation_id: "f282bb98-6d9c-446d-8ef6-1dacff261732",
        password: "sM1-rA9",
        phone_number: "+527031834673",
        name: "Sofía Ramírez Gómez",
        state: "creado",
        last_action: "creado",
        tier: "B",
        tag: "Familia",
        table: 91,
        notes: null,
        meal: null,
        side: "Santiago",
        companion_id: null,
        ticket: true,
        has_companion: false,
        last_action_by: false,
        type: "female"
    },
    {
        invitation_id: "f282bb98-6d9c-446d-8ef6-1dacff261732",
        password: "P7m-Xq8",
        phone_number: "+528317004583",
        name: "Sebastián Cruz Ruiz",
        state: "confirmado",
        last_action: "esperando",
        tier: "A",
        tag: "Trabajo",
        table: 14,
        notes: null,
        meal: null,
        side: "Santiago",
        companion_id: null,
        ticket: true,
        has_companion: false,
        last_action_by: false,
        type: "male"
    },
    {
        invitation_id: "f282bb98-6d9c-446d-8ef6-1dacff261732",
        password: "Y8d-Lm0",
        phone_number: "+520675714254",
        name: "Fernanda Rivera Gómez",
        state: "confirmado",
        last_action: "esperando",
        tier: "B",
        tag: "Trabajo",
        table: 89,
        notes: null,
        meal: null,
        side: "Ale",
        companion_id: null,
        ticket: true,
        has_companion: false,
        last_action_by: false,
        type: "female"
    },
    {
        invitation_id: "f282bb98-6d9c-446d-8ef6-1dacff261732",
        password: "W1p-Nm5",
        phone_number: "+523835324476",
        name: "Regina Reyes García",
        state: "confirmado",
        last_action: "esperando",
        tier: "A",
        tag: "Amigos",
        table: 13,
        notes: null,
        meal: null,
        side: "Ale",
        companion_id: null,
        ticket: true,
        has_companion: false,
        last_action_by: false,
        type: "female"
    },
    {
        invitation_id: "f282bb98-6d9c-446d-8ef6-1dacff261732",
        password: "A6k-Tv1",
        phone_number: "+524451832187",
        name: "Andrés Rivera Díaz",
        state: "confirmado",
        last_action: "esperando",
        tier: "C",
        tag: "Familia",
        table: 88,
        notes: null,
        meal: null,
        side: "Ale",
        companion_id: null,
        ticket: true,
        has_companion: false,
        last_action_by: false,
        type: "male"
    },
    {
        invitation_id: "f282bb98-6d9c-446d-8ef6-1dacff261732",
        password: "Z4x-Rm2",
        phone_number: "+523424597690",
        name: "Camila García López",
        state: "creado",
        last_action: "creado",
        tier: "A",
        tag: "Trabajo",
        table: 20,
        notes: null,
        meal: null,
        side: "Santiago",
        companion_id: null,
        ticket: true,
        has_companion: false,
        last_action_by: false,
        type: "female"
    },
    {
        invitation_id: "f282bb98-6d9c-446d-8ef6-1dacff261732",
        password: "G2s-Kw9",
        phone_number: "+521472674894",
        name: "Ana Ruiz Aguilar",
        state: "esperando",
        last_action: "creado",
        tier: "A",
        tag: "Amigos",
        table: 89,
        notes: null,
        meal: null,
        side: "Ale",
        companion_id: null,
        ticket: true,
        has_companion: false,
        last_action_by: false,
        type: "female"
    },
    {
        invitation_id: "f282bb98-6d9c-446d-8ef6-1dacff261732",
        password: "k5Q-Ln8",
        phone_number: "+523154377128",
        name: "Daniela Flores García",
        state: "esperando",
        last_action: "creado",
        tier: "A",
        tag: "Familia",
        table: 12,
        notes: null,
        meal: null,
        side: "Ale",
        companion_id: null,
        ticket: true,
        has_companion: false,
        last_action_by: false,
        type: "female"
    },
    {
        invitation_id: "f282bb98-6d9c-446d-8ef6-1dacff261732",
        password: "r8V-Dx2",
        phone_number: "+523243689055",
        name: "Emilio Torres Flores",
        state: "confirmado",
        last_action: "esperando",
        tier: "A",
        tag: "Trabajo",
        table: 93,
        notes: null,
        meal: null,
        side: "Santiago",
        companion_id: null,
        ticket: true,
        has_companion: false,
        last_action_by: false,
        type: "male"
    },
    {
        invitation_id: "f282bb98-6d9c-446d-8ef6-1dacff261732",
        password: "P3m-Wr7",
        phone_number: "+526945070106",
        name: "Lucía Hernández Navarro",
        state: "confirmado",
        last_action: "esperando",
        tier: "B",
        tag: "Trabajo",
        table: 13,
        notes: null,
        meal: null,
        side: "Santiago",
        companion_id: null,
        ticket: true,
        has_companion: false,
        last_action_by: false,
        type: "female"
    },
    {
        invitation_id: "f282bb98-6d9c-446d-8ef6-1dacff261732",
        password: "n7X-Km4",
        phone_number: "+523378910864",
        name: "Santiago Mendoza Ruiz",
        state: "creado",
        last_action: "creado",
        tier: "A",
        tag: "Amigos",
        table: 21,
        notes: null,
        meal: null,
        side: "Santiago",
        companion_id: null,
        ticket: true,
        has_companion: false,
        last_action_by: false,
        type: "male"
    },
    {
        invitation_id: "f282bb98-6d9c-446d-8ef6-1dacff261732",
        password: "H5q-Jz6",
        phone_number: "+527325198067",
        name: "Mariana González Reyes",
        state: "creado",
        last_action: "creado",
        tier: "A",
        tag: "Amigos",
        table: 18,
        notes: null,
        meal: null,
        side: "Ale",
        companion_id: null,
        ticket: true,
        has_companion: false,
        last_action_by: false,
        type: "female"
    },
    {
        invitation_id: "f282bb98-6d9c-446d-8ef6-1dacff261732",
        password: "L2a-Vw0",
        phone_number: "+522758018237",
        name: "Paula Reyes García",
        state: "confirmado",
        last_action: "esperando",
        tier: "B",
        tag: "Trabajo",
        table: 90,
        notes: null,
        meal: null,
        side: "Ale",
        companion_id: null,
        ticket: true,
        has_companion: false,
        last_action_by: false,
        type: "female"
    },
    {
        invitation_id: "f282bb98-6d9c-446d-8ef6-1dacff261732",
        password: "D9r-Xm5",
        phone_number: "+525095373159",
        name: "Emiliano Hernández López",
        state: "esperando",
        last_action: "creado",
        tier: "B",
        tag: "Trabajo",
        table: 20,
        notes: null,
        meal: null,
        side: "Santiago",
        companion_id: null,
        ticket: true,
        has_companion: false,
        last_action_by: false,
        type: "male"
    },
    {
        invitation_id: "f282bb98-6d9c-446d-8ef6-1dacff261732",
        password: "W8n-Qf4",
        phone_number: "+526148802087",
        name: "Ximena Castillo Díaz",
        state: "confirmado",
        last_action: "esperando",
        tier: "A",
        tag: "Familia",
        table: 93,
        notes: null,
        meal: null,
        side: "Ale",
        companion_id: null,
        ticket: true,
        has_companion: false,
        last_action_by: false,
        type: "female"
    },
    {
        invitation_id: "f282bb98-6d9c-446d-8ef6-1dacff261732",
        password: "z3M-Rk7",
        phone_number: "+522342650942",
        name: "Mariana Cruz Gómez",
        state: "confirmado",
        last_action: "esperando",
        tier: "B",
        tag: "Amigos",
        table: 92,
        notes: null,
        meal: null,
        side: "Santiago",
        companion_id: null,
        ticket: true,
        has_companion: false,
        last_action_by: false,
        type: "female"
    },
    {
        invitation_id: "f282bb98-6d9c-446d-8ef6-1dacff261732",
        password: "f4K-Nr1",
        phone_number: "+528961748244",
        name: "Camila Vázquez Ruiz",
        state: "confirmado",
        last_action: "esperando",
        tier: "A",
        tag: "Trabajo",
        table: 19,
        notes: null,
        meal: null,
        side: "Ale",
        companion_id: null,
        ticket: true,
        has_companion: false,
        last_action_by: false,
        type: "female"
    },
    {
        invitation_id: "f282bb98-6d9c-446d-8ef6-1dacff261732",
        password: "B1d-Xt9",
        phone_number: "+522196178968",
        name: "Emilio González Ruiz",
        state: "creado",
        last_action: "creado",
        tier: "D",
        tag: "Trabajo",
        table: 87,
        notes: null,
        meal: null,
        side: "Santiago",
        companion_id: null,
        ticket: true,
        has_companion: false,
        last_action_by: false,
        type: "male"
    },
    {
        invitation_id: "f282bb98-6d9c-446d-8ef6-1dacff261732",
        password: "p7S-Lv2",
        phone_number: "+527862840208",
        name: "Valentina Ruiz García",
        state: "confirmado",
        last_action: "esperando",
        tier: "A",
        tag: "Trabajo",
        table: 12,
        notes: null,
        meal: null,
        side: "Ale",
        companion_id: null,
        ticket: true,
        has_companion: false,
        last_action_by: false,
        type: "female"
    },
    {
        invitation_id: "f282bb98-6d9c-446d-8ef6-1dacff261732",
        password: "K4m-Rx7",
        phone_number: "+520549230447",
        name: "Andrea Díaz Cruz",
        state: "confirmado",
        last_action: "esperando",
        tier: "C",
        tag: "Familia",
        table: 21,
        notes: null,
        meal: null,
        side: "Santiago",
        companion_id: null,
        ticket: true,
        has_companion: false,
        last_action_by: false,
        type: "female"
    },
    {
        invitation_id: "f282bb98-6d9c-446d-8ef6-1dacff261732",
        password: "N5w-Ta8",
        phone_number: "+525618632292",
        name: "Rodrigo Ruiz Hernández",
        state: "confirmado",
        last_action: "esperando",
        tier: "B",
        tag: "Trabajo",
        table: 91,
        notes: null,
        meal: null,
        side: "Santiago",
        companion_id: null,
        ticket: true,
        has_companion: false,
        last_action_by: false,
        type: "male"
    },
    {
        invitation_id: "f282bb98-6d9c-446d-8ef6-1dacff261732",
        password: "X2c-Mq4",
        phone_number: "+527572845961",
        name: "Natalia Reyes Ruiz",
        state: "creado",
        last_action: "creado",
        tier: "A",
        tag: "Trabajo",
        table: 18,
        notes: null,
        meal: null,
        side: "Ale",
        companion_id: null,
        ticket: true,
        has_companion: false,
        last_action_by: false,
        type: "female"
    },
    {
        invitation_id: "f282bb98-6d9c-446d-8ef6-1dacff261732",
        password: "J1r-Vm6",
        phone_number: "+523523217353",
        name: "Paula Morales Díaz",
        state: "confirmado",
        last_action: "esperando",
        tier: "B",
        tag: "Amigos",
        table: 87,
        notes: null,
        meal: null,
        side: "Ale",
        companion_id: null,
        ticket: true,
        has_companion: false,
        last_action_by: false,
        type: "female"
    },
    {
        invitation_id: "f282bb98-6d9c-446d-8ef6-1dacff261732",
        password: "Q8n-Ls5",
        phone_number: "+529166854184",
        name: "Isabella Ramírez Ruiz",
        state: "creado",
        last_action: "creado",
        tier: "B",
        tag: "Trabajo",
        table: 12,
        notes: null,
        meal: null,
        side: "Santiago",
        companion_id: null,
        ticket: true,
        has_companion: false,
        last_action_by: false,
        type: "female"
    },
    {
        invitation_id: "f282bb98-6d9c-446d-8ef6-1dacff261732",
        password: "A9k-Px2",
        phone_number: "+522097798587",
        name: "Mariana Ruiz López",
        state: "confirmado",
        last_action: "esperando",
        tier: "A",
        tag: "Trabajo",
        table: 19,
        notes: null,
        meal: null,
        side: "Santiago",
        companion_id: null,
        ticket: true,
        has_companion: false,
        last_action_by: false,
        type: "female"
    },
    {
        invitation_id: "f282bb98-6d9c-446d-8ef6-1dacff261732",
        password: "c7V-Nm1",
        phone_number: "+521818742917",
        name: "Mateo Ruiz Díaz",
        state: "esperando",
        last_action: "creado",
        tier: "B",
        tag: "Familia",
        table: 92,
        notes: null,
        meal: null,
        side: "Ale",
        companion_id: null,
        ticket: true,
        has_companion: false,
        last_action_by: false,
        type: "male"
    },
    {
        invitation_id: "f282bb98-6d9c-446d-8ef6-1dacff261732",
        password: "R2m-Zx9",
        phone_number: "+524251187794",
        name: "Regina Díaz Rivera",
        state: "confirmado",
        last_action: "esperando",
        tier: "D",
        tag: "Trabajo",
        table: 93,
        notes: null,
        meal: null,
        side: "Santiago",
        companion_id: null,
        ticket: true,
        has_companion: false,
        last_action_by: false,
        type: "female"
    },
    {
        invitation_id: "f282bb98-6d9c-446d-8ef6-1dacff261732",
        password: "W6a-Tr5",
        phone_number: "+529957092870",
        name: "Paula Ruiz Gómez",
        state: "confirmado",
        last_action: "esperando",
        tier: "B",
        tag: "Amigos",
        table: 14,
        notes: null,
        meal: null,
        side: "Santiago",
        companion_id: null,
        ticket: true,
        has_companion: false,
        last_action_by: false,
        type: "female"
    },
    {
        invitation_id: "f282bb98-6d9c-446d-8ef6-1dacff261732",
        password: "m3P-Lx8",
        phone_number: "+529764975809",
        name: "Luis Mendoza Cruz",
        state: "creado",
        last_action: "creado",
        tier: "B",
        tag: "Amigos",
        table: 20,
        notes: null,
        meal: null,
        side: "Ale",
        companion_id: null,
        ticket: true,
        has_companion: false,
        last_action_by: false,
        type: "male"
    },
    {
        invitation_id: "f282bb98-6d9c-446d-8ef6-1dacff261732",
        password: "T9n-Kr4",
        phone_number: "+526380379461",
        name: "Victoria Gómez Cruz",
        state: "confirmado",
        last_action: "esperando",
        tier: "A",
        tag: "Familia",
        table: 89,
        notes: null,
        meal: null,
        side: "Ale",
        companion_id: null,
        ticket: true,
        has_companion: false,
        last_action_by: false,
        type: "female"
    },
    {
        invitation_id: "f282bb98-6d9c-446d-8ef6-1dacff261732",
        password: "j8D-Pq6",
        phone_number: "+524717554387",
        name: "Camila Reyes Ramírez",
        state: "esperando",
        last_action: "creado",
        tier: "A",
        tag: "Trabajo",
        table: 91,
        notes: null,
        meal: null,
        side: "Ale",
        companion_id: null,
        ticket: true,
        has_companion: false,
        last_action_by: false,
        type: "female"
    },
    {
        invitation_id: "f282bb98-6d9c-446d-8ef6-1dacff261732",
        password: "H7x-Lm3",
        phone_number: "+527082819733",
        name: "Sebastián Mendoza García",
        state: "confirmado",
        last_action: "esperando",
        tier: "A",
        tag: "Trabajo",
        table: 90,
        notes: null,
        meal: null,
        side: "Ale",
        companion_id: null,
        ticket: true,
        has_companion: false,
        last_action_by: false,
        type: "male"
    },
    {
        invitation_id: "f282bb98-6d9c-446d-8ef6-1dacff261732",
        password: "Q1m-Rv8",
        phone_number: "+520164040320",
        name: "Ximena Rivera Hernández",
        state: "confirmado",
        last_action: "esperando",
        tier: "B",
        tag: "Trabajo",
        table: 88,
        notes: null,
        meal: null,
        side: "Santiago",
        companion_id: null,
        ticket: true,
        has_companion: false,
        last_action_by: false,
        type: "female"
    },
    {
        invitation_id: "f282bb98-6d9c-446d-8ef6-1dacff261732",
        password: "P6a-Nk2",
        phone_number: "+521522343398",
        name: "Mariana Ruiz Torres",
        state: "creado",
        last_action: "creado",
        tier: "A",
        tag: "Trabajo",
        table: 19,
        notes: null,
        meal: null,
        side: "Ale",
        companion_id: null,
        ticket: true,
        has_companion: false,
        last_action_by: false,
        type: "female"
    },
    {
        invitation_id: "f282bb98-6d9c-446d-8ef6-1dacff261732",
        password: "z4T-Mq7",
        phone_number: "+529478616729",
        name: "Leonardo Cruz Ramírez",
        state: "confirmado",
        last_action: "esperando",
        tier: "A",
        tag: "Familia",
        table: 87,
        notes: null,
        meal: null,
        side: "Ale",
        companion_id: null,
        ticket: true,
        has_companion: false,
        last_action_by: false,
        type: "male"
    },
    {
        invitation_id: "f282bb98-6d9c-446d-8ef6-1dacff261732",
        password: "L5r-Xn1",
        phone_number: "+527068609063",
        name: "Valentina Ruiz Martínez",
        state: "creado",
        last_action: "creado",
        tier: "A",
        tag: "Trabajo",
        table: 14,
        notes: null,
        meal: null,
        side: "Ale",
        companion_id: null,
        ticket: true,
        has_companion: false,
        last_action_by: false,
        type: "female"
    },
    {
        invitation_id: "f282bb98-6d9c-446d-8ef6-1dacff261732",
        password: "B8m-Tv4",
        phone_number: "+529682445584",
        name: "Carla Ruiz Gómez",
        state: "confirmado",
        last_action: "esperando",
        tier: "C",
        tag: "Familia",
        table: 88,
        notes: null,
        meal: null,
        side: "Santiago",
        companion_id: null,
        ticket: true,
        has_companion: false,
        last_action_by: false,
        type: "female"
    },
    {
        invitation_id: "f282bb98-6d9c-446d-8ef6-1dacff261732",
        password: "N2q-Px7",
        phone_number: "+525167593245",
        name: "Diego Flores Ruiz",
        state: "confirmado",
        last_action: "esperando",
        tier: "D",
        tag: "Trabajo",
        table: 12,
        notes: null,
        meal: null,
        side: "Santiago",
        companion_id: null,
        ticket: true,
        has_companion: false,
        last_action_by: false,
        type: "male"
    },
    {
        invitation_id: "f282bb98-6d9c-446d-8ef6-1dacff261732",
        password: "M4k-Lr0",
        phone_number: "+527004302991",
        name: "Isabella Ramírez Gómez",
        state: "esperando",
        last_action: "creado",
        tier: "B",
        tag: "Amigos",
        table: 92,
        notes: null,
        meal: null,
        side: "Ale",
        companion_id: null,
        ticket: true,
        has_companion: false,
        last_action_by: false,
        type: "female"
    },
    {
        invitation_id: "f282bb98-6d9c-446d-8ef6-1dacff261732",
        password: "q7W-Nm2",
        phone_number: "+522825461679",
        name: "Ana Mendoza Ruiz",
        state: "confirmado",
        last_action: "esperando",
        tier: "A",
        tag: "Trabajo",
        table: 93,
        notes: null,
        meal: null,
        side: "Santiago",
        companion_id: null,
        ticket: true,
        has_companion: false,
        last_action_by: false,
        type: "female"
    },
    {
        invitation_id: "f282bb98-6d9c-446d-8ef6-1dacff261732",
        password: "S3x-Kq8",
        phone_number: "+523854957381",
        name: "Rodrigo Ramírez Flores",
        state: "creado",
        last_action: "creado",
        tier: "B",
        tag: "Amigos",
        table: 13,
        notes: null,
        meal: null,
        side: "Ale",
        companion_id: null,
        ticket: true,
        has_companion: false,
        last_action_by: false,
        type: "male"
    },
    {
        invitation_id: "f282bb98-6d9c-446d-8ef6-1dacff261732",
        password: "X1n-Rt5",
        phone_number: "+529511730623",
        name: "Sofía Rivera Ruiz",
        state: "confirmado",
        last_action: "esperando",
        tier: "B",
        tag: "Trabajo",
        table: 20,
        notes: null,
        meal: null,
        side: "Santiago",
        companion_id: null,
        ticket: true,
        has_companion: false,
        last_action_by: false,
        type: "female"
    },
    {
        invitation_id: "f282bb98-6d9c-446d-8ef6-1dacff261732",
        password: "D5m-Xp1",
        phone_number: "+528937298675",
        name: "Camila Ruiz Flores",
        state: "creado",
        last_action: "creado",
        tier: "A",
        tag: "Trabajo",
        table: 21,
        notes: null,
        meal: null,
        side: "Ale",
        companion_id: null,
        ticket: true,
        has_companion: false,
        last_action_by: false,
        type: "female"
    },
    {
        invitation_id: "f282bb98-6d9c-446d-8ef6-1dacff261732",
        password: "A8q-Ln6",
        phone_number: "+529481750871",
        name: "Mateo Gómez Cruz",
        state: "confirmado",
        last_action: "esperando",
        tier: "A",
        tag: "Trabajo",
        table: 91,
        notes: null,
        meal: null,
        side: "Santiago",
        companion_id: null,
        ticket: true,
        has_companion: false,
        last_action_by: false,
        type: "male"
    },
    {
        invitation_id: "f282bb98-6d9c-446d-8ef6-1dacff261732",
        password: "m2R-Vx9",
        phone_number: "+523619576817",
        name: "Renata Ruiz García",
        state: "confirmado",
        last_action: "esperando",
        tier: "B",
        tag: "Amigos",
        table: 14,
        notes: null,
        meal: null,
        side: "Ale",
        companion_id: null,
        ticket: true,
        has_companion: false,
        last_action_by: false,
        type: "female"
    },
    {
        invitation_id: "f282bb98-6d9c-446d-8ef6-1dacff261732",
        password: "H4t-Km7",
        phone_number: "+529307555251",
        name: "Dani Cruz Reyes",
        state: "confirmado",
        last_action: "esperando",
        tier: "C",
        tag: "Familia",
        table: 19,
        notes: null,
        meal: null,
        side: "Ale",
        companion_id: null,
        ticket: true,
        has_companion: false,
        last_action_by: false,
        type: "child"
    },
    {
        invitation_id: "f282bb98-6d9c-446d-8ef6-1dacff261732",
        password: "Q7m-Ra3",
        phone_number: "+522341877535",
        name: "Daniela Ruiz Hernández",
        state: "esperando",
        last_action: "creado",
        tier: "A",
        tag: "Trabajo",
        table: 18,
        notes: null,
        meal: null,
        side: "Santiago",
        companion_id: null,
        ticket: true,
        has_companion: false,
        last_action_by: false,
        type: "female"
    },
    {
        invitation_id: "f282bb98-6d9c-446d-8ef6-1dacff261732",
        password: "P9x-Lq2",
        phone_number: "+522522469228",
        name: "Hugo Ruiz Gómez",
        state: "confirmado",
        last_action: "esperando",
        tier: "A",
        tag: "Trabajo",
        table: 87,
        notes: null,
        meal: null,
        side: "Ale",
        companion_id: null,
        ticket: true,
        has_companion: false,
        last_action_by: false,
        type: "male"
    },
    {
        invitation_id: "f282bb98-6d9c-446d-8ef6-1dacff261732",
        password: "z6N-Tm4",
        phone_number: "+526150857510",
        name: "Natalia Ruiz Reyes",
        state: "confirmado",
        last_action: "esperando",
        tier: "B",
        tag: "Familia",
        table: 13,
        notes: null,
        meal: null,
        side: "Ale",
        companion_id: null,
        ticket: true,
        has_companion: false,
        last_action_by: false,
        type: "female"
    },
    {
        invitation_id: "f282bb98-6d9c-446d-8ef6-1dacff261732",
        password: "L9s-Pk1",
        phone_number: "+529910924905",
        name: "Andrea Gómez Díaz",
        state: "creado",
        last_action: "creado",
        tier: "D",
        tag: "Trabajo",
        table: 12,
        notes: null,
        meal: null,
        side: "Santiago",
        companion_id: null,
        ticket: true,
        has_companion: false,
        last_action_by: false,
        type: "female"
    },
    {
        invitation_id: "f282bb98-6d9c-446d-8ef6-1dacff261732",
        password: "V3m-Rx8",
        phone_number: "+525773621524",
        name: "Daniel González Ruiz",
        state: "confirmado",
        last_action: "esperando",
        tier: "A",
        tag: "Trabajo",
        table: 92,
        notes: null,
        meal: null,
        side: "Santiago",
        companion_id: null,
        ticket: true,
        has_companion: false,
        last_action_by: false,
        type: "male"
    },
    {
        invitation_id: "f282bb98-6d9c-446d-8ef6-1dacff261732",
        password: "B2n-Lv5",
        phone_number: "+523692585393",
        name: "Sara Ruiz Flores",
        state: "creado",
        last_action: "creado",
        tier: "B",
        tag: "Familia",
        table: 93,
        notes: null,
        meal: null,
        side: "Ale",
        companion_id: null,
        ticket: true,
        has_companion: false,
        last_action_by: false,
        type: "female"
    },
    {
        invitation_id: "f282bb98-6d9c-446d-8ef6-1dacff261732",
        password: "K1x-Mq7",
        phone_number: "+528839033963",
        name: "Joaquín Cruz Ruiz",
        state: "confirmado",
        last_action: "esperando",
        tier: "B",
        tag: "Trabajo",
        table: 89,
        notes: null,
        meal: null,
        side: "Ale",
        companion_id: null,
        ticket: true,
        has_companion: false,
        last_action_by: false,
        type: "male"
    },
    {
        invitation_id: "f282bb98-6d9c-446d-8ef6-1dacff261732",
        password: "R4a-Tn9",
        phone_number: "+527094014372",
        name: "Victoria Ruiz Mendoza",
        state: "confirmado",
        last_action: "esperando",
        tier: "C",
        tag: "Trabajo",
        table: 90,
        notes: null,
        meal: null,
        side: "Santiago",
        companion_id: null,
        ticket: true,
        has_companion: false,
        last_action_by: false,
        type: "female"
    },
    {
        invitation_id: "f282bb98-6d9c-446d-8ef6-1dacff261732",
        password: "m8Q-Lr3",
        phone_number: "+528175349192",
        name: "Gael Ruiz Flores",
        state: "confirmado",
        last_action: "esperando",
        tier: "A",
        tag: "Familia",
        table: 88,
        notes: null,
        meal: null,
        side: "Santiago",
        companion_id: null,
        ticket: true,
        has_companion: false,
        last_action_by: false,
        type: "male"
    },
    {
        invitation_id: "f282bb98-6d9c-446d-8ef6-1dacff261732",
        password: "T2m-Vx6",
        phone_number: "+526651561062",
        name: "Ana Ruiz Mendoza",
        state: "esperando",
        last_action: "creado",
        tier: "A",
        tag: "Trabajo",
        table: 19,
        notes: null,
        meal: null,
        side: "Ale",
        companion_id: null,
        ticket: true,
        has_companion: false,
        last_action_by: false,
        type: "female"
    },
    {
        invitation_id: "f282bb98-6d9c-446d-8ef6-1dacff261732",
        password: "N7p-Km4",
        phone_number: "+529654654155",
        name: "Valentina Ramírez Ruiz",
        state: "confirmado",
        last_action: "esperando",
        tier: "A",
        tag: "Amigos",
        table: 91,
        notes: null,
        meal: null,
        side: "Ale",
        companion_id: null,
        ticket: true,
        has_companion: false,
        last_action_by: false,
        type: "female"
    },
    {
        invitation_id: "f282bb98-6d9c-446d-8ef6-1dacff261732",
        password: "P5q-Ra1",
        phone_number: "+523013089918",
        name: "Lucía Ruiz Gómez",
        state: "creado",
        last_action: "creado",
        tier: "B",
        tag: "Familia",
        table: 14,
        notes: null,
        meal: null,
        side: "Santiago",
        companion_id: null,
        ticket: true,
        has_companion: false,
        last_action_by: false,
        type: "female"
    },
    {
        invitation_id: "f282bb98-6d9c-446d-8ef6-1dacff261732",
        password: "V9x-Ln2",
        phone_number: "+527432510014",
        name: "Pablo Ruiz Mendoza",
        state: "creado",
        last_action: "creado",
        tier: "B",
        tag: "Amigos",
        table: 20,
        notes: null,
        meal: null,
        side: "Ale",
        companion_id: null,
        ticket: true,
        has_companion: false,
        last_action_by: false,
        type: "male"
    },
    {
        invitation_id: "f282bb98-6d9c-446d-8ef6-1dacff261732",
        password: "J3m-Tq5",
        phone_number: "+522990645873",
        name: "Andrea Mendoza Ruiz",
        state: "confirmado",
        last_action: "esperando",
        tier: "A",
        tag: "Trabajo",
        table: 18,
        notes: null,
        meal: null,
        side: "Santiago",
        companion_id: null,
        ticket: true,
        has_companion: false,
        last_action_by: false,
        type: "female"
    },
    {
        invitation_id: "f282bb98-6d9c-446d-8ef6-1dacff261732",
        password: "K8r-Mv7",
        phone_number: "+526582603809",
        name: "Isabella Ruiz Mendoza",
        state: "esperando",
        last_action: "creado",
        tier: "A",
        tag: "Familia",
        table: 87,
        notes: null,
        meal: null,
        side: "Ale",
        companion_id: null,
        ticket: true,
        has_companion: false,
        last_action_by: false,
        type: "female"
    },
    {
        invitation_id: "f282bb98-6d9c-446d-8ef6-1dacff261732",
        password: "W2n-Lx4",
        phone_number: "+529145147598",
        name: "Santi Ruiz Cruz",
        state: "confirmado",
        last_action: "esperando",
        tier: "D",
        tag: "Trabajo",
        table: 12,
        notes: null,
        meal: null,
        side: "Santiago",
        companion_id: null,
        ticket: true,
        has_companion: false,
        last_action_by: false,
        type: "child"
    },
    {
        invitation_id: "f282bb98-6d9c-446d-8ef6-1dacff261732",
        password: "P4q-Nm8",
        phone_number: "+520247210115",
        name: "Carla Ruiz Díaz",
        state: "confirmado",
        last_action: "esperando",
        tier: "B",
        tag: "Trabajo",
        table: 21,
        notes: null,
        meal: null,
        side: "Ale",
        companion_id: null,
        ticket: true,
        has_companion: false,
        last_action_by: false,
        type: "female"
    },
    {
        invitation_id: "f282bb98-6d9c-446d-8ef6-1dacff261732",
        password: "A1x-Rt6",
        phone_number: "+528054390239",
        name: "Luis Ruiz Gómez",
        state: "confirmado",
        last_action: "esperando",
        tier: "C",
        tag: "Familia",
        table: 13,
        notes: null,
        meal: null,
        side: "Ale",
        companion_id: null,
        ticket: true,
        has_companion: false,
        last_action_by: false,
        type: "male"
    },
    {
        invitation_id: "f282bb98-6d9c-446d-8ef6-1dacff261732",
        password: "M7m-Pq2",
        phone_number: "+529434198774",
        name: "Fernanda Ruiz Reyes",
        state: "creado",
        last_action: "creado",
        tier: "B",
        tag: "Familia",
        table: 92,
        notes: null,
        meal: null,
        side: "Santiago",
        companion_id: null,
        ticket: true,
        has_companion: false,
        last_action_by: false,
        type: "female"
    },
    {
        invitation_id: "f282bb98-6d9c-446d-8ef6-1dacff261732",
        password: "D4n-Xv5",
        phone_number: "+524869107415",
        name: "Andrea Ruiz Flores",
        state: "creado",
        last_action: "creado",
        tier: "B",
        tag: "Amigos",
        table: 90,
        notes: null,
        meal: null,
        side: "Ale",
        companion_id: null,
        ticket: true,
        has_companion: false,
        last_action_by: false,
        type: "female"
    },
    {
        invitation_id: "f282bb98-6d9c-446d-8ef6-1dacff261732",
        password: "T8q-Km1",
        phone_number: "+525666420440",
        name: "Benjamín Ruiz Cruz",
        state: "esperando",
        last_action: "creado",
        tier: "B",
        tag: "Trabajo",
        table: 93,
        notes: null,
        meal: null,
        side: "Santiago",
        companion_id: null,
        ticket: true,
        has_companion: false,
        last_action_by: false,
        type: "male"
    },
    {
        invitation_id: "f282bb98-6d9c-446d-8ef6-1dacff261732",
        password: "R5m-Ln7",
        phone_number: "+523037093218",
        name: "Regina Flores Ruiz",
        state: "creado",
        last_action: "creado",
        tier: "A",
        tag: "Trabajo",
        table: 88,
        notes: null,
        meal: null,
        side: "Santiago",
        companion_id: null,
        ticket: true,
        has_companion: false,
        last_action_by: false,
        type: "female"
    }
]

// const insertGuests = async () => {
//     const { data, error } = await supabase
//         .from('guests')
//         .insert(guestsList)

//     if (error) {
//         console.error('Error insertando guests:', error)
//         return
//     }

//     console.log('Guests insertados correctamente:', data)
// }
