export * from './Cover'
export * from './DressCode'
export * from './Family'
export * from './Gallery'
export * from './Generals'
export * from './Greeting'
export * from './Itinerary'
export * from './Notices'
export * from './Quote'
export * from './TableGifts'

// export * from './CoverDev'
// // export * from './DressCode'
// export * from './FamilyDev'
// // export * from './Gallery'
// // export * from './Generals'
// export * from './GreetingDev'
// export * from './Itinerary'
// export * from './Notices'
// export * from './Quote'
// export * from './TableGifts'