-- Migración: catálogo de texturas centralizado en Supabase
--
-- Corre este script manualmente en el SQL Editor del dashboard de Supabase
-- del proyecto real de iattend (no se puede correr desde este entorno).
--
-- Antes de correr el INSERT de más abajo:
--   1. Sube las 11 imágenes actuales a una carpeta "Textures/" dentro del
--      bucket público "assets" (mismo bucket que usan Covers/Quote/Dresscode).
--      Los archivos son idénticos en ambos repos, usa por ejemplo los de
--      iattend-events/public/assets/textures/*.
--   2. Por cada imagen, copia la URL pública (Storage > assets > Textures >
--      archivo > "Get URL") y reemplaza los placeholders <BUCKET_URL> abajo.
--
-- El id de cada fila coincide a propósito con el índice 0-10 que ya usan las
-- invitaciones existentes en generals.texture — así ninguna invitación activa
-- necesita cambiar de dato, solo cambia de dónde se lee la textura.

create table public.textures (
  id          bigint generated by default as identity primary key,
  name        text not null,
  image_url   text not null,
  opacity     numeric not null default 1,
  blend       text not null default 'multiply',
  filter      text,
  sort_order  integer not null default 0,
  is_active   boolean not null default true,
  created_at  timestamptz not null default now()
);

alter table public.textures enable row level security;

-- Lectura pública: ambas apps (iattend-vite, iattend-events) leen con la anon key.
create policy "textures_select_public" on public.textures
  for select using (true);

-- Escritura solo para usuarios autenticados (el Admin panel exige login).
-- Si el rol admin se valida distinto hoy (revisa las policies existentes de
-- colaboradores_interesados, que ya se edita desde AdminPage.jsx con la anon
-- key), ajusta esta condición para que coincida.
create policy "textures_write_authenticated" on public.textures
  for all using (auth.role() = 'authenticated')
  with check (auth.role() = 'authenticated');

-- Seed: los 11 valores actuales, id explícito 0-10 para igualar los índices
-- de generals.texture que ya existen en invitaciones activas.
insert into public.textures (id, name, image_url, opacity, blend, filter, sort_order) values
(0,  'Papel',    '<BUCKET_URL>/assets/Textures/paper.jpg',    1,   'multiply', 'grayscale(1) contrast(1) brightness(1)',   0),
(1,  'Pared',    '<BUCKET_URL>/assets/Textures/pared.jpg',    0.5, 'multiply', 'grayscale(1) contrast(1) brightness(1)',   1),
(2,  'Papel 2',  '<BUCKET_URL>/assets/Textures/paper-2.jpg',  0.5, 'multiply', 'grayscale(1) contrast(1) brightness(1)',   2),
(3,  'Textil',   '<BUCKET_URL>/assets/Textures/textile.jpg',  0.5, 'multiply', 'grayscale(1) contrast(1) brightness(1)',   3),
(4,  'Grunge',   '<BUCKET_URL>/assets/Textures/grunge.jpg',   0.5, 'multiply', 'grayscale(1) contrast(1) brightness(1)',   4),
(5,  'Arrugado', '<BUCKET_URL>/assets/Textures/crumpled.jpg', 0.5, 'multiply', 'grayscale(1) contrast(1) brightness(1)',   5),
(6,  'Algodón',  '<BUCKET_URL>/assets/Textures/cotton.jpg',   0.5, 'multiply', 'grayscale(1) contrast(1.1) brightness(1)', 6),
(7,  'Cuero',    '<BUCKET_URL>/assets/Textures/leather.jpg',  0.5, 'multiply', 'grayscale(1) contrast(1.1) brightness(1)', 7),
(8,  'Revista',  '<BUCKET_URL>/assets/Textures/magazine.jpg', 0.5, 'multiply', 'grayscale(1) contrast(1.1) brightness(1)', 8),
(9,  'Flores',   '<BUCKET_URL>/assets/Textures/flowers.jpeg', 0.5, 'multiply', 'grayscale(1) contrast(1.1) brightness(1)', 9),
(10, 'Árboles',  '<BUCKET_URL>/assets/Textures/trees.jpg',    0.4, 'multiply', 'grayscale(1) contrast(1.2) brightness(1)', 10);
-- Nota: 'Árboles' usa opacity 0.4 / contrast(1.2), el valor que hoy está en
-- producción en iattend-events. iattend-vite tenía 0.5 / contrast(1.1) para
-- esta misma textura -- ya eran inconsistentes entre los dos repos antes de
-- esta migración. Ajustable en cualquier momento desde el tab Texturas del Admin.

-- Continuar el autoincrement desde 11 para las texturas nuevas que se agreguen
-- después desde el Admin.
alter sequence public.textures_id_seq restart with 11;
