-- ============================================================================
-- Seating chart v2 — Fase 0 (prerrequisitos de base de datos)
--
-- NO SE HA EJECUTADO. Revisar antes de correr en producción.
-- Cada bloque es idempotente y se puede correr por separado.
--
-- Referencias al spec: §3.2 (locked), §3.3 (trigger de liberación),
-- §3.5 (layout_elements), §2.5 (FK de guests.table), §3.6 (unique de number).
-- ============================================================================


-- ────────────────────────────────────────────────────────────────────────────
-- §3.2 — tables.locked
-- Sin esto, "reacomodar mesas" es destructivo: el generador reposicionaría
-- la mesa que el usuario ya resolvió a mano. El generador debe tratar las
-- mesas bloqueadas como obstáculos fijos, igual que la pista.
-- ────────────────────────────────────────────────────────────────────────────
ALTER TABLE public.tables
  ADD COLUMN IF NOT EXISTS locked boolean NOT NULL DEFAULT false;


-- ────────────────────────────────────────────────────────────────────────────
-- §3.5 — layout_elements (elementos del salón)
--
-- Tabla propia porque entrada, baños, barra y escenario necesitan ancho, alto
-- y rotación propios, y tables.size / tables.vertical no dan para eso.
--
-- Diferencias deliberadas respecto a `tables`:
--   · ambos timestamps CON zona (tables.last_update_at es sin zona — §2.1)
--   · `type` es text libre, no enum, para agregar elementos sin migración
--   · `locked` desde el inicio: un elemento del salón casi nunca se mueve
--   · sin `size` ni `number`: no cuenta lugares y no se numera
-- ────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.layout_elements (
  id             bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  invitation_id  uuid NOT NULL,
  type           text NOT NULL,   -- dancefloor | stage | entrance | restroom | bar | dj | custom
  label          text NULL,       -- texto visible; si es null se usa el default del type
  x              numeric NOT NULL,
  y              numeric NOT NULL,
  width          numeric NOT NULL,
  height         numeric NOT NULL,
  rotation       numeric NOT NULL DEFAULT 0,
  locked         boolean NOT NULL DEFAULT false,
  created_at     timestamptz NOT NULL DEFAULT now(),
  last_update_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT layout_elements_pkey PRIMARY KEY (id),
  CONSTRAINT layout_elements_invitation_id_fkey
    FOREIGN KEY (invitation_id) REFERENCES public.invitations (id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS layout_elements_invitation_id_idx
  ON public.layout_elements (invitation_id);

ALTER TABLE public.layout_elements ENABLE ROW LEVEL SECURITY;

-- ⚠️ GRANT antes que RLS. Postgres revisa el GRANT primero, así que sin esto
-- la lectura desde el frontend con la anon key falla con
-- "permission denied for table" (42501) aunque exista la policy.
-- Mismo tropiezo que con invitation_versions — ver docs/reviews-feedback.md.
GRANT SELECT, INSERT, UPDATE, DELETE ON public.layout_elements TO anon, authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.layout_elements_id_seq TO anon, authenticated;

-- Policy espejo de la que ya tenga `tables`. Verificar con:
--   SELECT policyname, cmd, qual FROM pg_policies WHERE tablename = 'tables';
-- y replicarla aquí antes de dar la tabla por lista.
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies
    WHERE schemaname = 'public'
      AND tablename  = 'layout_elements'
      AND policyname = 'layout_elements_all'
  ) THEN
    CREATE POLICY layout_elements_all ON public.layout_elements
      FOR ALL TO anon, authenticated
      USING (true) WITH CHECK (true);
  END IF;
END $$;


-- ────────────────────────────────────────────────────────────────────────────
-- §2.5 — FK de guests.table → tables.id
--
-- guests.table guarda tables.id (no `number`, que se repite entre eventos).
-- Con FK, perder un id falla ruidosamente; sin FK, se corrompe en silencio.
--
-- ON DELETE SET NULL y no CASCADE: borrar una mesa nunca debe borrar invitados.
-- Hoy deleteTableAndAdjust() en TablesPage.jsx ya libera a mano antes de borrar;
-- esto es la red de seguridad para cualquier otra ruta (Lia, backend, SQL suelto).
--
-- ⚠️ Antes de correr esto, verificar que no haya huérfanos:
--   SELECT g.id, g."table" FROM public.guests g
--   LEFT JOIN public.tables t ON t.id = g."table"
--   WHERE g."table" IS NOT NULL AND t.id IS NULL;
-- Si devuelve filas, limpiarlas (SET "table" = NULL) o la constraint no entra.
-- ────────────────────────────────────────────────────────────────────────────
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'guests_table_fkey'
      AND conrelid = 'public.guests'::regclass
  ) THEN
    ALTER TABLE public.guests
      ADD CONSTRAINT guests_table_fkey
      FOREIGN KEY ("table") REFERENCES public.tables (id) ON DELETE SET NULL;
  END IF;
END $$;


-- ────────────────────────────────────────────────────────────────────────────
-- §3.3 — Liberar la mesa cuando un confirmado cancela
--
-- Tiene que ser un trigger, no lógica de frontend: el state cambia desde dos
-- lados independientes — el organizador desde iattend-vite, y el invitado
-- haciendo RSVP en iattend-events, que escribe directo a Supabase con la anon
-- key sin pasar por el backend. Si la limpieza viviera en iattend-vite, el caso
-- más común (el invitado cancelando desde su propia invitación) no se cubriría.
--
-- Alcance decidido: SOLO 'rechazado'. Si el organizador corrige de 'confirmado'
-- a 'esperando', esa persona conserva su mesa sin estar confirmada — es el mismo
-- lugar fantasma por otra puerta, y se dejó fuera a propósito.
--
-- Los acompañantes NO cascadean: tienen su propio state y no dependen del
-- principal. El trigger toca solo la fila que cambió.
--
-- ⚠️ Antes de crear esto, revisar qué triggers hay hoy sobre guests:
--   SELECT tgname, pg_get_triggerdef(oid) FROM pg_trigger
--   WHERE tgrelid = 'public.guests'::regclass AND NOT tgisinternal;
-- En particular si trg_guest_state_notification sigue activo, para no acumular
-- lógica que nadie sabe que existe.
--
-- SOBRE EL AVISO AL ORGANIZADOR: este trigger deliberadamente NO escribe un
-- mensaje. No existe una tabla de notificaciones en el proyecto — el centro de
-- notificaciones del organizador (NotificationCard.jsx) deriva cada tarjeta de
-- una fila de `guests` leyendo state / last_action / last_action_by. Así que el
-- aviso se resuelve en el cliente, no aquí. Ver la nota en la §3.3 del handoff.
-- ────────────────────────────────────────────────────────────────────────────
CREATE OR REPLACE FUNCTION public.release_table_on_rejection()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  UPDATE public.guests
     SET "table" = NULL
   WHERE id = NEW.id;

  RETURN NULL;  -- AFTER trigger: el valor de retorno se ignora
END;
$$;

DROP TRIGGER IF EXISTS trg_release_table_on_rejection ON public.guests;

CREATE TRIGGER trg_release_table_on_rejection
  AFTER UPDATE OF state ON public.guests
  FOR EACH ROW
  WHEN (
    NEW.state = 'rechazado'
    AND OLD.state IS DISTINCT FROM 'rechazado'
    AND NEW."table" IS NOT NULL
  )
  EXECUTE FUNCTION public.release_table_on_rejection();


-- ────────────────────────────────────────────────────────────────────────────
-- §3.6 — UNIQUE (invitation_id, number)
--
-- Verificado el 2026-08-26 contra la base real: CERO duplicados hoy, así que
-- la constraint entra sin limpieza previa.
--
-- Se deja COMENTADO a propósito. Hoy el frontend ya avisa visualmente cuando
-- hay números repetidos (isRepeated en DynamicTable.jsx pinta la mesa en rojo)
-- en vez de bloquear el guardado. Activar esta constraint convierte ese aviso
-- suave en un error duro de Postgres que el frontend todavía no maneja —
-- primero hay que darle a updateTable() un mensaje de error decente.
--
-- La pista de baile queda fuera del índice: comparte el espacio de numeración
-- con las mesas y colisionaría sin razón.
-- ────────────────────────────────────────────────────────────────────────────
-- CREATE UNIQUE INDEX IF NOT EXISTS tables_invitation_number_uniq
--   ON public.tables (invitation_id, number)
--   WHERE shape IS DISTINCT FROM 'dance';
