export const languages_select = [
    { value: 'EN-US', label: '🇺🇸 Inglés (Americano)' },
    { value: 'EN-GB', label: '🇬🇧 Inglés (Británico)' },
    { value: 'FR', label: '🇫🇷 Francés' },
    { value: 'DE', label: '🇩🇪 Alemán' },
    { value: 'PT-BR', label: '🇧🇷 Portugués (Brasil)' },
    { value: 'PT-PT', label: '🇵🇹 Portugués (Portugal)' },
    { value: 'IT', label: '🇮🇹 Italiano' },
    { value: 'ZH-HANS', label: '🇨🇳 Chino (Simplificado)' },
    { value: 'ZH-HANT', label: '🇹🇼 Chino (Tradicional)' },
    { value: 'JA', label: '🇯🇵 Japonés' },
    { value: 'KO', label: '🇰🇷 Coreano' },
    { value: 'RU', label: '🇷🇺 Ruso' },
    { value: 'AR', label: '🇸🇦 Árabe' },
    { value: 'NL', label: '🇳🇱 Neerlandés' },
    { value: 'PL', label: '🇵🇱 Polaco' },
    { value: 'TR', label: '🇹🇷 Turco' },
    { value: 'SV', label: '🇸🇪 Sueco' },
    { value: 'DA', label: '🇩🇰 Danés' },
    { value: 'FI', label: '🇫🇮 Finlandés' },
    { value: 'NB', label: '🇳🇴 Noruego (Bokmål)' },
    { value: 'CS', label: '🇨🇿 Checo' },
    { value: 'HU', label: '🇭🇺 Húngaro' },
    { value: 'RO', label: '🇷🇴 Rumano' },
    { value: 'SK', label: '🇸🇰 Eslovaco' },
    { value: 'SL', label: '🇸🇮 Esloveno' },
    { value: 'BG', label: '🇧🇬 Búlgaro' },
    { value: 'EL', label: '🇬🇷 Griego' },
    { value: 'ET', label: '🇪🇪 Estonio' },
    { value: 'LV', label: '🇱🇻 Letón' },
    { value: 'LT', label: '🇱🇹 Lituano' },
    { value: 'ID', label: '🇮🇩 Indonesio' },
    { value: 'UK', label: '🇺🇦 Ucraniano' },
]